FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install --no-cache-dir ipython black flake8

CMD ["streamlit", "run", "streamlit_app.py"]
