version: "3.9"

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "streamlit_app.py"]

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["pytest"]
