apiVersion: v1
kind: Service
metadata:
  name: kidney-streamlit-service
spec:
  selector:
    app: kidney-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort

